#!/usr/bin/env ruby

puts "Loading general libraries..."
require 'yaml'
require 'logger'
require 'ostruct'
require 'ftools'
require 'rubygems'
require 'zip/zip'
puts "Loading database libraries..."
require 'active_support'
require 'active_record'
puts "Loading Rails libraries..."
ActiveRecord::Base.allow_concurrency = true
require File.dirname(__FILE__) + '/../config/environment'
require 'optparse'
require 'ostruct'

options = OpenStruct.new
OptionParser.new do |opts|
  opts.banner = "Usage: script/drbserver [options]"
  
  opts.on( "-h", "--host HOST", String,
           "IP to bind to" ) do |opt|
    options.host = opt
  end
  
  opts.on( "-p", "--port PORT", Integer,
           "port number to listen on" ) do |opt|
    options.port = opt.to_i
  end

  opts.on_tail("-H", "--help", "Show this message") do
    puts opts
    exit
  end

  opts.on_tail("--version", "Show version") do
    puts OptionParser::Version.join('.')
    exit
  end
end.parse!

Judge::Server::Server.start_server(options)
